/**
 * Effect report generator.
 *
 * Runs the full engine over the v2 dashboard fixtures and writes:
 *   - REPORT.md   : findings, grounded critiques, apply delta, computed data
 *                   slices, and the observable event timeline.
 *   - report.html : a self-contained vega-embed gallery of the before/after
 *                   specs and a real computed cross-filter slice.
 *
 * Runs offline by default (deterministic template phrasing) so it is fully
 * reproducible without an API key; with a gateway token the phrasing comes from
 * the LLM (guardrail unchanged).
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { Critique, TraceEvent } from "../src/contracts.ts";
import { GatewayClient } from "../src/llm/client.ts";
import { hasToken } from "../src/llm/gateway.ts";
import { Tracer } from "../src/trace.ts";
import { runApply, runCritique } from "../src/engine.ts";
import { applyProposals } from "../src/apply/index.ts";
import { computeCrossFilterSlice } from "../src/compute/crossFilter.ts";
import { dashboardBoard, dashboardSpecMap } from "../fixtures/specs.ts";
import { PROJECT_ROOT } from "../src/llm/gateway.ts";

const useLLM = process.env.RE_API_DISABLE_LLM !== "1" && hasToken();
const client = useLLM ? new GatewayClient() : undefined;

function timeline(events: TraceEvent[]): string {
  const t0 = events[0]?.ts ?? 0;
  return events
    .map((e) => {
      const dt = `+${String(e.ts - t0).padStart(4, " ")}ms`;
      return `| ${dt} | \`${e.phase}\` | ${(e.message ?? "").replace(/\|/g, "\\|")} |`;
    })
    .join("\n");
}

function critiqueBlock(c: Critique): string {
  return [
    `### ${c.title}  \`${c.proposal.kind}\``,
    `- **Issue:** ${c.issue}`,
    `- **Rationale:** ${c.rationale}`,
    `- **Evidence (grounding):** ${c.evidence}`,
    `- **Suggestion:** ${c.suggestion}`,
    `- **Dimension:** \`${c.dimension}\` · surface \`${c.surface}\`${c.interactionKind ? ` · interaction \`${c.interactionKind}\`` : ""}`,
    `- **Grounded in finding:** \`${c.findingId}\``,
  ].join("\n");
}

async function main() {
  const specMap = dashboardSpecMap();
  const board = dashboardBoard();

  const critTracer = new Tracer("report-critique", { logDir: null });
  const crit = await runCritique(
    { version: 1, context: { goal: "Track team throughput and project health", audience: "Delivery leads" }, specMap, board },
    critTracer,
    { client },
  );

  // The engine's apply pipeline (transform -> compile-gate -> compute) owns the
  // interaction slice; visual/narrative fixes are applied by the frontend, so we
  // exercise apply over just the interaction critiques here.
  const interactionIds = crit.critiques.filter((c) => c.dimension === "interaction").map((c) => c.id);
  const applyTracer = new Tracer("report-apply", { logDir: null });
  const apply = await runApply(
    {
      version: 1,
      context: {},
      specMap,
      board,
      critiques: crit.critiques,
      selectedRecommendationIds: interactionIds,
    },
    applyTracer,
    { client },
  );

  // A concrete computed slice for the gallery (real numbers, engine-computed).
  const appliedVelocity = apply.specMap["task-velocity"];
  const appliedStatus = apply.specMap["project-status"];
  const velEng = computeCrossFilterSlice(appliedVelocity, "department", "Eng");
  const statusEng = computeCrossFilterSlice(appliedStatus, "department", "Eng");

  // ---- REPORT.md ----
  const md = [
    "# re_api — effect report",
    "",
    `Generated by \`npm run report\`. LLM phrasing: **${useLLM ? "on (gateway)" : "off (deterministic templates)"}**.`,
    "",
    "This runs the real engine end-to-end over the v2 dashboard fixtures:",
    "**detect (deterministic) → generate (grounded) → apply → compile-gate → compute (real data) → re-evaluate**,",
    "emitting an observable event at every step.",
    "",
    "## 1. Findings (deterministic detection)",
    "",
    "| id | kind | severity | evidence |",
    "| --- | --- | --- | --- |",
    ...crit.findings.map(
      (f) => `| \`${f.id}\` | ${f.kind} | ${f.severity} | ${f.evidence.detail.replace(/\|/g, "\\|")} |`,
    ),
    "",
    "## 2. Critiques (grounded phrasing)",
    "",
    ...crit.critiques.map(critiqueBlock),
    "",
    "## 3. Apply → compute → re-evaluate",
    "",
    `- **Application order:** ${apply.applicationOrder.map((x) => `\`${x}\``).join(", ")}`,
    `- **Changed targets:** ${apply.changedTargets.map((x) => `\`${x}\``).join(", ")}`,
    `- **Compile gate:** ${apply.evaluationReport.compiled ? "passed" : "FAILED"} · rollback: ${apply.rollback.rolledBack}`,
    `- **Remaining findings after fixes:** ${apply.evaluationReport.remainingFindings}`,
    "",
    "**Engine-computed data slices (real numbers, not model-authored):**",
    "",
    ...apply.evaluationReport.computed.map((c) => `- ${c.note}`),
    "",
    "**Recommendation delta:**",
    "",
    "```json",
    JSON.stringify(apply.recommendationDelta, null, 2),
    "```",
    "",
    `New follow-up critique(s) introduced: ${apply.addedCritiques.map((c) => `\`${c.id}\` (${c.title})`).join(", ") || "none"}.`,
    "",
    "## 4. Observable event timeline",
    "",
    "### critique run",
    "",
    "| t | phase | message |",
    "| --- | --- | --- |",
    timeline(critTracer.events),
    "",
    "### apply run",
    "",
    "| t | phase | message |",
    "| --- | --- | --- |",
    timeline(applyTracer.events),
    "",
    "## 5. Concrete cross-filter compute (department = \"Eng\")",
    "",
    `- Task Velocity: ${velEng.rowsAfter}/${velEng.rowsBefore} rows, y-domain pinned to ${velEng.pinnedMax !== null ? Math.ceil(velEng.pinnedMax * 1.05) : "n/a"} (so the filtered line drops instead of rescaling).`,
    `- Project Status: ${statusEng.rowsAfter}/${statusEng.rowsBefore} rows.`,
    "",
    "See `report.html` for the rendered before/after gallery.",
    "",
    "## 6. Summary — what is real vs. mock",
    "",
    "**Real (this engine):**",
    "- Deterministic detection across every review dimension, each grounded in a machine-checkable fact:",
    "  - interaction — cross-filter gaps + missing tooltips from Vega-Lite spec structure;",
    "  - visual — missing KPI row (board chrome) + a shared brand hue across tiles (mark/scale colors);",
    "  - narrative — a generic heading + chart tiles lacking takeaway subtitles (board chrome).",
    "- Critique generation grounded in those findings; a guardrail rejects text that drifts to the wrong kind or fabricates numeric results, falling back to deterministic phrasing. No critique is hardcoded.",
    "- Applying a proposal as a real spec transform, gated by native `vega-lite` compile (rollback on failure).",
    "- Computing the real post-interaction data slice (per-value filter + pinned domain).",
    "- Re-evaluation by re-running detectors on the mutated spec map; living-recommendation delta.",
    "- Full observability: every phase (and each generation token) is emitted over SSE and to `runs/*.jsonl`.",
    "",
    "**Scope of the apply pipeline:**",
    "- The interaction dimension is wired end-to-end (transform → compile-gate → compute → re-evaluate).",
    "- Visual/narrative critiques are fully *detected and phrased* by the engine; their board mutations (KPI row, palette, title, subtitles) are applied by the v2 frontend, so they share the mock apply path.",
    "- Cross-view coordination between separately-rendered tiles remains a runtime concern (the v2 driver / compute step); the applied spec records intent via `usermeta.crossFilter`.",
    "",
    "**Next seams:**",
    "- Extend the engine apply pipeline to the visual/narrative proposals (each `proposalKind` plugs into apply/reevaluate unchanged).",
    "- Drive the live Vega `View` from the computed slice (Seam C) so the demo is genuinely engine-driven.",
    "",
  ].join("\n");

  writeFileSync(resolve(PROJECT_ROOT, "REPORT.md"), md);

  // ---- report.html ----
  const gallery = [
    { title: "Before — Task Velocity (line, no tooltip, no points)", spec: specMap["task-velocity"] },
    { title: "After — Task Velocity (tooltip + hover points)", spec: appliedVelocity },
    { title: "Computed — Task Velocity filtered to Eng (real slice, y pinned)", spec: velEng.spec },
    { title: "Before — Tasks by Department (looks selectable, inert)", spec: specMap["department-tasks"] },
    { title: "After — Tasks by Department (point selection + affordance)", spec: apply.specMap["department-tasks"] },
    { title: "Computed — Project Status filtered to Eng (real slice)", spec: statusEng.spec },
  ];

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>re_api — before / after gallery</title>
<script src="https://cdn.jsdelivr.net/npm/vega@6"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-lite@6"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-embed@7"></script>
<style>
  body{font:14px/1.5 ui-sans-serif,system-ui,sans-serif;margin:0;background:#f6f8fc;color:#1e293b}
  header{padding:20px 28px;background:#0f1729;color:#e2e8f0}
  header h1{margin:0 0 4px;font-size:18px}
  header p{margin:0;color:#93a4c4;font-size:13px}
  .grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;padding:24px 28px}
  .card{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:14px 16px;box-shadow:0 1px 3px rgba(15,23,41,.05)}
  .card h2{margin:0 0 10px;font-size:13px;color:#334155;font-weight:600}
  @media (max-width:900px){.grid{grid-template-columns:1fr}}
</style>
</head>
<body>
<header>
  <h1>re_api — before / after gallery</h1>
  <p>Grounded interaction fixes over the VIZier v2 dashboard. "Computed" panels show real engine-filtered data, not model output.</p>
</header>
<div class="grid">
${gallery
  .map(
    (g, i) =>
      `  <div class="card"><h2>${g.title}</h2><div id="v${i}"></div></div>`,
  )
  .join("\n")}
</div>
<script>
  const specs = ${JSON.stringify(gallery.map((g) => g.spec))};
  specs.forEach((s, i) => vegaEmbed("#v" + i, s, { actions: false }).catch(console.error));
</script>
</body>
</html>`;

  writeFileSync(resolve(PROJECT_ROOT, "report.html"), html);

  console.log("Wrote REPORT.md and report.html");
  console.log(`LLM phrasing: ${useLLM ? "on" : "off (templates)"}`);
  console.log(`Findings: ${crit.findings.length} · Critiques: ${crit.critiques.length} · remaining after apply: ${apply.evaluationReport.remainingFindings}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
